services:
  app:
    restart: unless-stopped
    image: nayukidayo/dzznc:latest
    logging:
      driver: local
    ports:
      - '37211:3000'
    environment:
      - MQTT_URL=
      - MQTT_USER=
      - MQTT_PASS=
